# Generated by Django 6.0.4 on 2026-06-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        ('processos', '0006_conviteatribuicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='convite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='processos.conviteatribuicao'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentário'), ('colaborador', 'Colaborador'), ('conflito', 'Conflito de versão'), ('atribuicao', 'Atribuição'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
    ]
