# Generated by Django 6.0.4 on 2026-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_notificacao_convite_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentário'), ('colaborador', 'Colaborador'), ('conflito', 'Conflito de versão'), ('atribuicao', 'Atribuição'), ('assinatura', 'Assinatura'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
    ]
