# Generated by Django 6.0.4 on 2026-04-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('applicant', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(choices=[('REURB-S', 'REURB-S'), ('REURB-E', 'REURB-E')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible_name', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('technician_id', models.IntegerField(blank=True, null=True)),
                ('legal_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
