# Generated by Django 6.0.4 on 2026-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='processo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processo',
            name='protocol',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='protocolado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Iniciado', 'Iniciado'), ('Levantamento Técnico', 'Levantamento Técnico'), ('Análise Jurídica', 'Análise Jurídica'), ('Em Edital', 'Em Edital'), ('Diligência', 'Diligência'), ('Em Análise', 'Em Análise'), ('Aprovado', 'Aprovado'), ('Concluído', 'Concluído'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Arquivado', 'Arquivado')], default='Pendente', max_length=50),
        ),
        migrations.AddField(
            model_name='processo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='area',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processo',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='processo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='processo',
            name='modality',
            field=models.CharField(choices=[('REURB-S', 'REURB-S'), ('REURB-E', 'REURB-E')], default='REURB-S', max_length=20),
        ),
        migrations.AlterField(
            model_name='processo',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processo',
            name='responsible_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
