# Generated by Django 6.0.4 on 2026-05-12 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_processo_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='legal_id',
            field=models.ForeignKey(blank=True, db_column='legal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_juridico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processo',
            name='technician_id',
            field=models.ForeignKey(blank=True, db_column='technician_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_tecnico', to=settings.AUTH_USER_MODEL),
        ),
    ]
