# Generated by Django 6.0.4 on 2026-05-27 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_alter_processo_legal_id_alter_processo_technician_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('arquivo_adicionado', 'Arquivo adicionado'), ('arquivo_removido', 'Arquivo removido'), ('etapa_status', 'Status de etapa alterado'), ('equipe_alterada', 'Equipe alterada'), ('status_alterado', 'Status alterado'), ('processo_criado', 'Processo criado'), ('processo_protocolado', 'Processo protocolado')], max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='processos.processo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_processo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
