# Generated by Django 6.0.4 on 2026-05-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleadmin', '0002_seed_niveis_e_permissoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilacessousuario',
            options={'ordering': ['user__name', 'user__email'], 'verbose_name': 'Perfil de acesso do usuário', 'verbose_name_plural': 'Perfis de acesso dos usuários'},
        ),
    ]
