# Generated by Django 6.0.4 on 2026-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
