# Generated by Django 6.0.4 on 2026-04-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_customuser_permissions_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Gestor', 'Gestor'), ('Jurídico', 'Jurídico'), ('Técnico', 'Técnico'), ('Auditor', 'Auditor'), ('Atendente', 'Atendente')], default='Atendente', max_length=100),
        ),
    ]
