# Generated by Django 6.0.4 on 2026-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
