# Generated by Django 6.0.4 on 2026-05-27 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_customuser_name_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('permissao', models.CharField(choices=[('visualizar', 'Visualizar'), ('editar', 'Editar')], default='visualizar', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_equipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
