# Generated by Django 6.0.4 on 2026-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0007_perfil_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='access_flags',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permissions_data',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Gestor', 'Gestor'), ('Jurídico', 'Jurídico'), ('Técnico', 'Técnico'), ('Auditor', 'Auditor'), ('Atendente', 'Atendente')], default='Atendente', max_length=100),
        ),
    ]
