# Generated by Django 4.2.30 on 2026-06-08 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0009_ensure_customuser_permissions_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('provedor', models.CharField(choices=[('senha', 'Senha'), ('google', 'Google')], max_length=20)),
                ('sucesso', models.BooleanField(db_index=True, default=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tentativas_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['criado_em', 'sucesso'], name='autenticaca_criado__351ee1_idx'), models.Index(fields=['provedor', 'criado_em'], name='autenticaca_provedo_716a8b_idx')],
            },
        ),
    ]
