# Generated by Django 6.0.4 on 2026-05-13 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_convitedocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('comentario', 'Comentário'), ('assinatura', 'Assinatura'), ('finalizado', 'Finalizado'), ('colaborador_adicionado', 'Colaborador Adicionado'), ('colaborador_removido', 'Colaborador Removido'), ('status_alterado', 'Status Alterado')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('versao', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='documentos.documento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['documento', '-criado_em'], name='documentos__documen_9852d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PresencaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_acesso', models.DateTimeField(auto_now=True, db_index=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('documento', 'usuario')},
            },
        ),
    ]
