# Generated by Django 6.0.4 on 2026-05-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_auditoriadocumento_presencadocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariodocumento',
            name='pos_fim',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentariodocumento',
            name='pos_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentariodocumento',
            name='texto_selecionado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='presencadocumento',
            name='cursor_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
