# Generated by Django 6.0.4 on 2026-05-22 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_comentariodocumento_pos_fim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Notificação', 'Notificação'), ('Técnico', 'Técnico'), ('Titularidade', 'Titularidade'), ('Outro', 'Outro')], default='Outro', max_length=50)),
                ('versao', models.CharField(default='V1.0', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('conteudo', models.TextField()),
                ('campos', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
