# Generated by Django 6.0.4 on 2026-05-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_modelodocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodocumento',
            name='is_sistema',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
