# Generated by Django 6.0.4 on 2026-05-27 12:38

from django.db import migrations

MODELOS_SISTEMA = [
    {
        'nome':     'Portaria de Instauração',
        'tipo':     'Administrativo',
        'versao':   'V2.1',
        'descricao': 'Portaria de instauração do processo de regularização fundiária urbana.',
        'conteudo': (
            'PORTARIA DE INSTAURAÇÃO\n\n'
            'O proprietário {{nome}}, CPF {{cpf}}, {{cargo}}, residente em {{local}}, '
            'declara para os devidos fins que a área {{area}} está vinculada ao processo '
            'de regularização fundiária no endereço {{local}}.\n\n'
            'Data do documento: {{dataDocumento}}.\n'
            'Observações: {{observacoes}}.'
        ),
        'campos': [
            {'key': 'nome',          'label': 'Nome completo',     'type': 'text',     'required': True},
            {'key': 'cpf',           'label': 'CPF',               'type': 'cpf',      'required': True},
            {'key': 'cargo',         'label': 'Cargo',             'type': 'text',     'required': False},
            {'key': 'local',         'label': 'Endereço',          'type': 'text',     'required': True},
            {'key': 'area',          'label': 'Área',              'type': 'text',     'required': False},
            {'key': 'dataDocumento', 'label': 'Data do documento',  'type': 'date',     'required': False},
            {'key': 'observacoes',   'label': 'Observações',       'type': 'textarea', 'required': False},
        ],
    },
    {
        'nome':     'Notificação de Confrontantes',
        'tipo':     'Notificação',
        'versao':   'V1.5',
        'descricao': 'Notificação formal aos confrontantes da área em processo de regularização.',
        'conteudo': (
            'NOTIFICAÇÃO DE CONFRONTANTES\n\n'
            'Comunicamos que {{nome}}, CPF {{cpf}}, no cargo de {{cargo}}, '
            'notifica os confrontantes da área {{area}}, localizada em {{local}}, '
            'conforme processo {{protocolo}}.\n\n'
            'Data: {{dataDocumento}}.\n'
            'Observações: {{observacoes}}.'
        ),
        'campos': [
            {'key': 'nome',          'label': 'Nome completo',     'type': 'text',     'required': True},
            {'key': 'cpf',           'label': 'CPF',               'type': 'cpf',      'required': True},
            {'key': 'cargo',         'label': 'Cargo',             'type': 'text',     'required': False},
            {'key': 'local',         'label': 'Endereço',          'type': 'text',     'required': True},
            {'key': 'area',          'label': 'Área',              'type': 'text',     'required': False},
            {'key': 'protocolo',     'label': 'Protocolo',         'type': 'text',     'required': False},
            {'key': 'dataDocumento', 'label': 'Data do documento',  'type': 'date',     'required': False},
            {'key': 'observacoes',   'label': 'Observações',       'type': 'textarea', 'required': False},
        ],
    },
    {
        'nome':     'Relatório Técnico Social',
        'tipo':     'Técnico',
        'versao':   'V3.0',
        'descricao': 'Relatório de caracterização técnica e social da área para fins de REURB.',
        'conteudo': (
            'RELATÓRIO TÉCNICO SOCIAL\n\n'
            'Responsável: {{nome}} (CPF {{cpf}}), cargo {{cargo}}.\n\n'
            'Caracterização da área {{area}} em {{local}}.\n\n'
            'Conclusão preliminar: {{observacoes}}.\n'
            'Data do levantamento: {{dataDocumento}}.'
        ),
        'campos': [
            {'key': 'nome',          'label': 'Nome completo',     'type': 'text',     'required': True},
            {'key': 'cpf',           'label': 'CPF',               'type': 'cpf',      'required': True},
            {'key': 'cargo',         'label': 'Cargo',             'type': 'text',     'required': False},
            {'key': 'local',         'label': 'Endereço',          'type': 'text',     'required': True},
            {'key': 'area',          'label': 'Área',              'type': 'text',     'required': False},
            {'key': 'dataDocumento', 'label': 'Data do documento',  'type': 'date',     'required': False},
            {'key': 'observacoes',   'label': 'Observações',       'type': 'textarea', 'required': False},
        ],
    },
    {
        'nome':     'Auto de Demarcação Urbanística',
        'tipo':     'Técnico',
        'versao':   'V1.2',
        'descricao': 'Auto formal de demarcação do núcleo urbano informal para fins de REURB.',
        'conteudo': (
            'AUTO DE DEMARCAÇÃO URBANÍSTICA\n\n'
            'Aos {{dataDocumento}}, {{nome}}, CPF {{cpf}}, no cargo de {{cargo}}, '
            'lavra o presente auto para a área {{area}}, situada em {{local}}, '
            'protocolo {{protocolo}}.\n\n'
            'Informações complementares: {{observacoes}}.'
        ),
        'campos': [
            {'key': 'nome',          'label': 'Nome completo',     'type': 'text',     'required': True},
            {'key': 'cpf',           'label': 'CPF',               'type': 'cpf',      'required': True},
            {'key': 'cargo',         'label': 'Cargo',             'type': 'text',     'required': False},
            {'key': 'local',         'label': 'Endereço',          'type': 'text',     'required': True},
            {'key': 'area',          'label': 'Área',              'type': 'text',     'required': False},
            {'key': 'protocolo',     'label': 'Protocolo',         'type': 'text',     'required': False},
            {'key': 'dataDocumento', 'label': 'Data do documento',  'type': 'date',     'required': False},
            {'key': 'observacoes',   'label': 'Observações',       'type': 'textarea', 'required': False},
        ],
    },
    {
        'nome':     'Título de Legitimação Fundiária',
        'tipo':     'Titularidade',
        'versao':   'V4.2',
        'descricao': 'Título que reconhece e legitima a posse de unidade imobiliária em núcleo urbano informal.',
        'conteudo': (
            'TÍTULO DE LEGITIMAÇÃO FUNDIÁRIA\n\n'
            'Fica registrado que {{nome}}, CPF {{cpf}}, na função {{cargo}}, '
            'reconhece os dados da área {{area}} localizada em {{local}}, '
            'processo {{protocolo}}.\n\n'
            'Data de emissão: {{dataDocumento}}.\n'
            'Complemento: {{observacoes}}.'
        ),
        'campos': [
            {'key': 'nome',          'label': 'Nome completo',     'type': 'text',     'required': True},
            {'key': 'cpf',           'label': 'CPF',               'type': 'cpf',      'required': True},
            {'key': 'cargo',         'label': 'Cargo / Função',    'type': 'text',     'required': False},
            {'key': 'local',         'label': 'Endereço',          'type': 'text',     'required': True},
            {'key': 'area',          'label': 'Área',              'type': 'text',     'required': False},
            {'key': 'protocolo',     'label': 'Protocolo',         'type': 'text',     'required': False},
            {'key': 'dataDocumento', 'label': 'Data de emissão',   'type': 'date',     'required': False},
            {'key': 'observacoes',   'label': 'Complemento',       'type': 'textarea', 'required': False},
        ],
    },
]


def seed_modelos(apps, schema_editor):
    ModeloDocumento = apps.get_model('documentos', 'ModeloDocumento')
    for dados in MODELOS_SISTEMA:
        ModeloDocumento.objects.get_or_create(
            nome=dados['nome'],
            is_sistema=True,
            defaults={
                'tipo':      dados['tipo'],
                'versao':    dados['versao'],
                'descricao': dados['descricao'],
                'conteudo':  dados['conteudo'],
                'campos':    dados['campos'],
                'criado_por': None,
            },
        )


def remover_modelos(apps, schema_editor):
    ModeloDocumento = apps.get_model('documentos', 'ModeloDocumento')
    nomes = [m['nome'] for m in MODELOS_SISTEMA]
    ModeloDocumento.objects.filter(nome__in=nomes, is_sistema=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_modelo_is_sistema'),
    ]

    operations = [
        migrations.RunPython(seed_modelos, remover_modelos),
    ]
