# Generated by Django 6.0.4 on 2026-04-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Gestor', 'Gestor'), ('Jurídico', 'Jurídico'), ('Técnico', 'Técnico'), ('Auditor', 'Auditor'), ('Atendente', 'Atendente')], default='Atendente', max_length=20)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('quota_used', models.IntegerField(default=0)),
                ('quota_limit', models.IntegerField(default=100)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
    ]
