# Generated by Django 6.0.4 on 2026-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anexos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='etapa_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
